# Generated by Django 3.0.3 on 2020-06-22 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='headline',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 22, 12, 28, 43, 762341)),
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.CharField(default='sai', max_length=50),
        ),
    ]
