# Generated by Django 3.0.3 on 2020-06-27 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayview', '0002_auto_20200622_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='active',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 27, 23, 23, 40, 491668)),
        ),
    ]
