# Generated by Django 2.2.12 on 2020-11-01 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayview', '0003_auto_20200627_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 1, 13, 38, 24, 466589)),
        ),
        migrations.AlterField(
            model_name='article',
            name='reporter',
            field=models.CharField(default='vishnu', max_length=50),
        ),
    ]
